# Generated by Django 5.2 on 2025-09-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocktype_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockset',
            name='custom_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockset',
            name='custom_selling_price_retail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockset',
            name='custom_selling_price_wholesale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
