# Generated by Django 5.2 on 2025-09-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockset_custom_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockset',
            name='consumption_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How much base stock this set consumes (e.g., 5ml, 10ml).', max_digits=12, null=True),
        ),
    ]
