# Generated by Django 5.2 on 2025-09-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockset_consumption_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktype',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'None'), ('mtr', 'Meter'), ('ml', 'Milliliter')], default='', max_length=3, null=True),
        ),
    ]
